context.modules = [
{   name = libpipewire-module-combine-stream
    args = {
        combine.mode = sink
        node.name = "oficina_stereo"
        node.description = "Oficina estéreo"
        combine.latency-compensate = true
        combine.props = {
            audio.position = [ FL FR ]
        }
        stream.props = {
            stream.dont-remix = true
        }
        stream.rules = [
            { matches = [
                { media.class = "Audio/Sink"
                  node.description = "Oficina"
                }
            ]
              actions = { create-stream = {
                  audio.position = [ FL FR ]
                  combine.audio.position = [ FL FL ]
              } }
            }
            { matches = [
                { media.class = "Audio/Sink"
                  node.description = "Oficina (2)"
                }
            ]
              actions = { create-stream = {
                  audio.position = [ FL FR ]
                  combine.audio.position = [ FR FR ]
              } }
            }
        ]
    }
}
]
